[Profile]
profile_id = mevya
base_profile = fedora

[Profile Detection]
os_id = mevya
variant_id = mevya

[Bootloader]
efi_dir = fedora

[Network]
default_on_boot = FIRST_WIRED_WITH_LINK

[Storage]
default_scheme = BTRFS
btrfs_compression = zstd:1

[Localization]
use_geolocation = True
